server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///heima?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    name: provider  #\u5C06\u6765\u4F1A\u4F5C\u4E3A\u5FAE\u670D\u52A1\u7684\u540D\u79F0
mybatis:
  type-aliases-package: cn.jiyun.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true #\u670D\u52A1\u63D0\u4F9B\u65B9\u542F\u52A8\u65F6,\u4F1A\u68C0\u6D4B\u8BE5\u53C2\u6570\u662F\u5426\u4E3Atrue,\u4E3Atrue\u5219\u6CE8\u518C\u7ED9eureka
  instance:
    lease-expiration-duration-in-seconds: 15   #\u8FC7\u671F\u65F6\u95F4
    lease-renewal-interval-in-seconds: 5  #\u5FC3\u8DF3\u65F6\u95F4